export { WELCOME_TUTORIAL } from "./welcome";
export {
  DASHBOARD_TUTORIAL,
  PROJECTS_TUTORIAL,
  TASKS_TUTORIAL,
  STAKEHOLDERS_TUTORIAL,
  MEETINGS_TUTORIAL,
  TRANSCRIPTIONS_TUTORIAL,
  DOCUMENTS_TUTORIAL,
} from "./pages";
